image: node0.10

script:
  - npm -s install -g gulp bower
  - npm -s install
  - gulp build && gulp deploy:$DRONE_BRANCH

notify:

  slack:
    team: iteamsolutions
    channel: #marknad
    username: drone.io
    token: 8CucDNnAVELD0BBEErMnhobE
    on_started: false
    on_failure: true
    on_success: false

